<?php
    session_start();
    session_destroy();
    setcookie('userid','',time()-360000,'/');
    setcookie('userpic','',time()-360000,'/');
    unset($_COOKIE['userid']);
    unset($_COOKIE['userpic']);
    header('location:../login');
?>